In [1]:
import torch
print(torch.__version__)

2.5.1


In [2]:
if torch.cuda.is_available():
    print("GPU is available! Using GPU:")
    print(torch.cuda.get_device_name(0))
    # print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available! Using GPU:
NVIDIA GeForce GTX 1650


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)
a
# a[1][2]

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.4978, 0.5605, 0.5406],
        [0.5522, 0.1778, 0.9016]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.6483, 0.1416, 0.9485],
        [0.9112, 0.4021, 0.5269]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
# same shape as `x`, values can be anything
torch.empty_like(x)

tensor([[2338152646960,             0,             0],
        [            0,             0,             0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
# torch.rand_like(x) # must mention datatype
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [23]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [24]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [26]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [27]:
c = torch.tensor([1, -2, 3, -4])

In [28]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [31]:
# round
# not d.round / d.round_
torch.round(d)

tensor([2., 2., 4., 4.])

In [32]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [33]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [34]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.3000, 3.7000, 4.0000])

### 3. Reduction operation

In [35]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [36]:
# sum along columns
torch.sum(e)
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [37]:
# mean
# torch.mean(e)
# mean along col
# torch.mean(e, dim=0)
# mean along row
torch.mean(e, dim=1)

tensor([5., 3.])

In [38]:
# median
torch.median(e)

tensor(0.)

In [39]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [40]:
# product
torch.prod(e)

tensor(0.)

In [41]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [42]:
# variance
torch.var(e)

tensor(19.6000)

In [43]:
# argmax
torch.argmax(e)

tensor(5)

In [44]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [45]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [46]:
# matrix multiplcation
# torch.mm(f, g)       # 2-D Matrix multiplication
torch.matmul(f, g)     # n-D

tensor([[ 87, 119],
        [ 65,  99]])

In [47]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [48]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [49]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(-110.0000)

In [51]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [52]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [53]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [54]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [55]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [56]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [57]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [58]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [59]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [60]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [61]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [62]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [63]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [64]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [65]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [66]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [67]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [68]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [69]:
b = a

In [70]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [71]:
a[0][0] = 0

In [72]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [73]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [74]:
id(a)

2322572670160

In [75]:
id(b)

2322572670160

In [76]:
b = a.clone()

In [77]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [78]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [79]:
a[0][0] = 10

In [80]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [81]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [82]:
id(a)

2322572670160

In [83]:
id(b)

2322572841744

# Tensor Operations on GPU

In [84]:
torch.cuda.is_available()

True

In [85]:
gpu = torch.device('cuda')
gpu

device(type='cuda')

In [86]:
t1 = torch.rand(2,3)  #cpu

In [87]:
# torch.rand((2,3), device=gpu) #same
t2 = torch.rand(2,3, device=gpu)
t2

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [88]:
t3 = t1.to(gpu)  #copy from cpu to gpu, not inplace
t1, t3

(tensor([[0.2243, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]]),
 tensor([[0.2243, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]], device='cuda:0'))

### Speed comparison

In [89]:
import time

size = 10000 # Large size for performance comparison

# Create random matrices on CPU

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Perform matrix multiplication
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # "Matrix multiplication on CPU
cpu_time = time.time() - start_time

# Measure time on CPU
print(f"Time on CPU: {cpu_time:.4f} seconds")

# Check if GPU/CUDA is available
if torch.cuda.is_available():
    # Move matrices to GPU
    matrix_gpu1 = matrix_cpu1.to('cuda')
    matrix_gpu2 = matrix_cpu2.to('cuda')

    # Measure time on GPU
    start_time = time.time()
    result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
    
    # Synchronize to ensure all GPU operations are complete and calculate time
    torch.cuda.synchronize()
    gpu_time = time.time() - start_time

    print(f"Time taken on GPU: {gpu_time:.4f} seconds")
    print(f'Performance gain: {round(cpu_time / gpu_time)}')
else:
    print("CUDA is not available. GPU computation cannot be performed.")

Time on CPU: 20.8918 seconds
Time taken on GPU: 1.6398 seconds
Performance gain: 13


# Reshaping Tensors (not inplace)

In [90]:
a = torch.ones(4,6)
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [91]:
a.reshape(2,6,2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [92]:
a.reshape(-1,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [93]:
a.reshape(1,-1) #same as (1,24)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1.]])

In [94]:
# Flatten - 1D tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])

In [95]:
b = torch.randint(low=1,high=100,size=(2,3,4))
b

tensor([[[69, 85, 53, 61],
         [36, 55,  1, 96],
         [24, 93, 24, 45]],

        [[86, 31, 76, 27],
         [71, 44, 39,  6],
         [97, 95, 26, 11]]])

In [96]:
b.permute(2,0,1)

tensor([[[69, 36, 24],
         [86, 71, 97]],

        [[85, 55, 93],
         [31, 44, 95]],

        [[53,  1, 24],
         [76, 39, 26]],

        [[61, 96, 45],
         [27,  6, 11]]])

In [97]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [98]:
# Unsqueze -  dimension of size one inserted at the specified position.
c = torch.rand(226,226,3)  # Typical image size

In [99]:
c.unsqueeze(dim=0)

tensor([[[[0.2861, 0.7459, 0.8487],
          [0.4059, 0.2883, 0.2220],
          [0.6423, 0.7098, 0.5644],
          ...,
          [0.8170, 0.3172, 0.4378],
          [0.8047, 0.3651, 0.0630],
          [0.9183, 0.0861, 0.9756]],

         [[0.1175, 0.9696, 0.4014],
          [0.8289, 0.4343, 0.8286],
          [0.0097, 0.4689, 0.7481],
          ...,
          [0.7167, 0.5256, 0.8594],
          [0.4732, 0.2077, 0.9188],
          [0.7575, 0.8535, 0.5775]],

         [[0.4705, 0.8696, 0.3757],
          [0.1533, 0.9881, 0.4648],
          [0.2386, 0.8656, 0.7935],
          ...,
          [0.3768, 0.3613, 0.7167],
          [0.4770, 0.0998, 0.2141],
          [0.5962, 0.9068, 0.1834]],

         ...,

         [[0.5488, 0.2471, 0.2906],
          [0.5791, 0.2177, 0.4913],
          [0.5510, 0.8402, 0.1218],
          ...,
          [0.6777, 0.8650, 0.1008],
          [0.8294, 0.1528, 0.3117],
          [0.8750, 0.2646, 0.5109]],

         [[0.0817, 0.7453, 0.4627],
          [0.4627

In [100]:
c.unsqueeze(dim=2).shape

torch.Size([226, 226, 1, 3])

In [101]:
# Squeeze
d = torch.rand(1,20)
d

tensor([[0.6899, 0.9883, 0.2160, 0.4054, 0.5001, 0.2665, 0.4164, 0.0810, 0.5344,
         0.3673, 0.9286, 0.0528, 0.3753, 0.2057, 0.5643, 0.4419, 0.5215, 0.6743,
         0.0401, 0.7158]])

In [102]:
# d.squeeze(1) #Same as d
d.squeeze(0)

tensor([0.6899, 0.9883, 0.2160, 0.4054, 0.5001, 0.2665, 0.4164, 0.0810, 0.5344,
        0.3673, 0.9286, 0.0528, 0.3753, 0.2057, 0.5643, 0.4419, 0.5215, 0.6743,
        0.0401, 0.7158])

# Numpy <--> Tensor

In [103]:
import numpy as np

In [104]:
t = torch.tensor([5,4,42])
t , type(t)

(tensor([ 5,  4, 42]), torch.Tensor)

In [105]:
arr = t.numpy()
arr , type(arr)

(array([ 5,  4, 42], dtype=int64), numpy.ndarray)

In [106]:
a = np.random.randint(1,100,(5,2))
a

array([[40, 21],
       [65, 27],
       [43, 35],
       [75, 11],
       [ 1, 14]])

In [107]:
ta = torch.from_numpy(a) 
ta

tensor([[40, 21],
        [65, 27],
        [43, 35],
        [75, 11],
        [ 1, 14]], dtype=torch.int32)

In [108]:
ta_np = ta.numpy()
print(ta_np)

[[40 21]
 [65 27]
 [43 35]
 [75 11]
 [ 1 14]]
